[package]
org = "ballerina"
name = "persist"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["persist"]
repository = "https://github.com/ballerina-platform/module-ballerina-persist"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.29.jar"
scope="testOnly"

[[platform.java11.dependency]]
groupId = "io.ballerina.persist"
artifactId = "sql-persist"
version = "0.1.0"
path = "../native/build/libs/persist-native-0.1.0-SNAPSHOT.jar"
