[package]
org = "wso2"
name = "medical_center"
version = "0.1.0"

[[platform.java11.dependency]]
path = "../../ballerina/lib/mysql-connector-java-8.0.29.jar"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.29"
