[package]
org = "danesh"
name = "basic_entity"
version = "0.1.0"
distribution = "2201.1.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "persist"
version = "0.1.0"
repository = "local"
