name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 2201.[0-9]+.x
      - dependent-functions
    paths-ignore:
      - 'load-tests/**'
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          nexusUser: ${{ secrets.NEXUS_USERNAME }}
          nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          ./gradlew publishMavenJavaPublicationToWSO2NexusRepository --scan --no-daemon
